apiVersion: v1
kind: Service
metadata:
  name: mongodb
  labels:
    app: mongodb
spec:
  type: NodePort
  ports:
    - port: 27017
      targetPort: 27017
      nodePort: 30001  # NodePort for MongoDB
  selector:
    app: mongodb

